name: Deploy PKBI to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install & Build
        run: |
          pnpm install
          # Skip pengecekan database saat build
          pnpm run build
        env:
          # Gunakan URL dummy agar Prisma tidak error saat build
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/db"
          NEXT_TELEMETRY_DISABLED: 1

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/node_modules/**
            .git**
            src/**
